image:
  repository: ""
  tag: ""
  digest: ""
  pullPolicy: IfNotPresent

scaffold:
  enabled: false
  releaseId: graphblocks-deployment-chart
  accessNamespaces: []
  replicas: 1
  args: []
  env: []

serviceAccount:
  create: false
  name: ""

rbac:
  create: false
  clusterWide: false
  rules: []

podAnnotations: {}
podLabels: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
