{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | quote }}
  labels:
    app.kubernetes.io/name: graphblocks-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: Helm
{{- end }}
