{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graphblocks-operator.serviceAccountName" . | quote }}
  labels:
    app.kubernetes.io/name: graphblocks-operator
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end }}
