{{- if and .Values.scaffold.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graphblocks-deployment-chart.serviceAccountName" . | quote }}
  labels:
    app.kubernetes.io/name: graphblocks-deployment-chart
    app.kubernetes.io/component: controller-scaffold
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
{{- end }}
