from __future__ import annotations

from graphblocks.agent import (
    AgentLoopController,
    AgentLoopDecision,
    AgentLoopDisposition,
    AgentSpec,
    AgentState,
    AgentStateError,
    AgentStatePatch,
    AgentStatePatchOp,
    AgentStatePatchOpKind,
    AgentStateSchema,
    ToolFailurePolicy,
)
from graphblocks.conversation import ContentPart
from graphblocks.policy import (
    PolicyDecision,
    PolicyEffect,
    PolicyObligation,
    PolicyRequest,
    PrincipalRef,
)
from graphblocks.tools import (
    AdmittedToolCall,
    BlockToolImplementation,
    GraphRef,
    GraphToolImplementation,
    JsonSchema,
    JsonSchemaNode,
    JsonSchemaRef,
    McpToolImplementation,
    OpenApiToolImplementation,
    RemoteToolImplementation,
    ResolvedTool,
    ResourceRef,
    ToolAdmissionError,
    ToolApproval,
    ToolApprovalError,
    ToolApprovalRecord,
    ToolApprovalRequest,
    ToolApprovalStatus,
    ToolBinding,
    ToolCall,
    ToolCallDraft,
    ToolCallDraftStatus,
    ToolCallError,
    ToolCallStatus,
    ToolCancellation,
    ToolCatalog,
    ToolDefinition,
    ToolEffect,
    ToolEffectOutcome,
    ToolExecutionCancellationPolicy,
    ToolExecutionFailurePolicy,
    ToolExecutionPlan,
    ToolExecutionPlanError,
    ToolExecutionState,
    ToolIdempotency,
    ToolImplementation,
    ToolPlanCall,
    ToolResolutionError,
    ToolResolutionScope,
    ToolResult,
    ToolResultEvent,
    ToolResultEventKind,
    ToolResultMode,
    ToolResultStatus,
    ToolResultStreamError,
    ToolResultStreamState,
    ToolResultValidationError,
    ToolSchemaRegistry,
    ToolSchemaRegistryError,
    ToolSchemaValidationError,
    admit_tool_call,
    build_before_tool_or_effect_policy_request,
    validate_tool_result_for_model,
)


def evaluate_native_tool_execution_plan(
    plan: dict[str, object],
    operations: object,
) -> dict[str, object]:
    from graphblocks_runtime import evaluate_tool_execution_plan

    return evaluate_tool_execution_plan(plan, operations)


def evaluate_native_sequential_tool_queue(
    queue: dict[str, object],
    operations: object,
) -> dict[str, object]:
    from graphblocks_runtime import evaluate_sequential_tool_queue

    return evaluate_sequential_tool_queue(queue, operations)


__all__ = [
    "AdmittedToolCall",
    "AgentLoopController",
    "AgentLoopDecision",
    "AgentLoopDisposition",
    "AgentSpec",
    "AgentState",
    "AgentStateError",
    "AgentStatePatch",
    "AgentStatePatchOp",
    "AgentStatePatchOpKind",
    "AgentStateSchema",
    "BlockToolImplementation",
    "ContentPart",
    "GraphRef",
    "GraphToolImplementation",
    "JsonSchema",
    "JsonSchemaNode",
    "JsonSchemaRef",
    "McpToolImplementation",
    "OpenApiToolImplementation",
    "PolicyDecision",
    "PolicyEffect",
    "PolicyObligation",
    "PolicyRequest",
    "PrincipalRef",
    "RemoteToolImplementation",
    "ResolvedTool",
    "ResourceRef",
    "ToolAdmissionError",
    "ToolApproval",
    "ToolApprovalError",
    "ToolApprovalRecord",
    "ToolApprovalRequest",
    "ToolApprovalStatus",
    "ToolBinding",
    "ToolCall",
    "ToolCallDraft",
    "ToolCallDraftStatus",
    "ToolCallError",
    "ToolCallStatus",
    "ToolCancellation",
    "ToolCatalog",
    "ToolDefinition",
    "ToolEffect",
    "ToolEffectOutcome",
    "ToolExecutionCancellationPolicy",
    "ToolExecutionFailurePolicy",
    "ToolExecutionPlan",
    "ToolExecutionPlanError",
    "ToolFailurePolicy",
    "ToolExecutionState",
    "ToolIdempotency",
    "ToolImplementation",
    "ToolPlanCall",
    "ToolResolutionError",
    "ToolResolutionScope",
    "ToolResult",
    "ToolResultEvent",
    "ToolResultEventKind",
    "ToolResultMode",
    "ToolResultStatus",
    "ToolResultStreamError",
    "ToolResultStreamState",
    "ToolResultValidationError",
    "ToolSchemaRegistry",
    "ToolSchemaRegistryError",
    "ToolSchemaValidationError",
    "admit_tool_call",
    "build_before_tool_or_effect_policy_request",
    "evaluate_native_sequential_tool_queue",
    "evaluate_native_tool_execution_plan",
    "validate_tool_result_for_model",
]
