use graphblocks_runtime_core::output_policy::{
    DeliveryMode, DraftDisposition, DurableResult, FlushBoundary, OutputDisposition,
    PendingToolCallsDisposition, ProviderCancellation, TerminalReason, ViolationAction,
};
use graphblocks_runtime_core::tool::{
    ToolApproval, ToolCancellation, ToolEffect, ToolIdempotency, ToolResultMode,
};
use graphblocks_runtime_core::tool_call::{ToolCallDraftStatus, ToolCallStatus};
use graphblocks_runtime_core::tool_result::{ToolEffectOutcome, ToolResultStatus};

#[test]
fn runtime_enums_expose_canonical_policy_and_tool_literals() {
    assert_eq!(
        [
            OutputDisposition::Allow,
            OutputDisposition::Hold,
            OutputDisposition::Redact,
            OutputDisposition::Replace,
            OutputDisposition::AbortResponse,
            OutputDisposition::AbortTurn,
            OutputDisposition::DenyCommit,
        ]
        .into_iter()
        .map(OutputDisposition::as_str)
        .collect::<Vec<_>>(),
        vec![
            "allow",
            "hold",
            "redact",
            "replace",
            "abort_response",
            "abort_turn",
            "deny_commit",
        ]
    );
    assert_eq!(
        [
            ProviderCancellation::None,
            ProviderCancellation::Request,
            ProviderCancellation::RequiredIfSupported,
        ]
        .into_iter()
        .map(ProviderCancellation::as_str)
        .collect::<Vec<_>>(),
        vec!["none", "request", "required_if_supported"]
    );
    assert_eq!(
        [
            DraftDisposition::Keep,
            DraftDisposition::MarkIncomplete,
            DraftDisposition::Retract,
        ]
        .into_iter()
        .map(DraftDisposition::as_str)
        .collect::<Vec<_>>(),
        vec!["keep", "mark_incomplete", "retract"]
    );
    assert_eq!(
        [
            PendingToolCallsDisposition::Keep,
            PendingToolCallsDisposition::Deny,
            PendingToolCallsDisposition::CancelAdmitted,
        ]
        .into_iter()
        .map(PendingToolCallsDisposition::as_str)
        .collect::<Vec<_>>(),
        vec!["keep", "deny", "cancel_admitted"]
    );
    assert_eq!(
        [
            DeliveryMode::BufferUntilCommit,
            DeliveryMode::BoundedHoldback,
            DeliveryMode::ImmediateDraft,
        ]
        .into_iter()
        .map(DeliveryMode::as_str)
        .collect::<Vec<_>>(),
        vec!["buffer_until_commit", "bounded_holdback", "immediate_draft"]
    );
    assert_eq!(
        [
            FlushBoundary::Token,
            FlushBoundary::Sentence,
            FlushBoundary::Paragraph,
            FlushBoundary::ContentPart,
            FlushBoundary::ToolCall,
            FlushBoundary::Response,
        ]
        .into_iter()
        .map(FlushBoundary::as_str)
        .collect::<Vec<_>>(),
        vec![
            "token",
            "sentence",
            "paragraph",
            "content_part",
            "tool_call",
            "response",
        ]
    );
    assert_eq!(
        [
            ViolationAction::AbortResponse,
            ViolationAction::AbortTurn,
            ViolationAction::Redact,
            ViolationAction::Replace,
        ]
        .into_iter()
        .map(ViolationAction::as_str)
        .collect::<Vec<_>>(),
        vec!["abort_response", "abort_turn", "redact", "replace"]
    );
    assert_eq!(
        [
            TerminalReason::PolicyDenied,
            TerminalReason::BudgetExhausted,
            TerminalReason::Cancelled,
            TerminalReason::ClientDisconnected,
        ]
        .into_iter()
        .map(TerminalReason::as_str)
        .collect::<Vec<_>>(),
        vec![
            "policy_denied",
            "budget_exhausted",
            "cancelled",
            "client_disconnected",
        ]
    );
    assert_eq!(
        [
            DurableResult::None,
            DurableResult::Incomplete,
            DurableResult::Partial,
        ]
        .into_iter()
        .map(DurableResult::as_str)
        .collect::<Vec<_>>(),
        vec!["none", "incomplete", "partial"]
    );

    assert_eq!(
        [
            ToolApproval::Never,
            ToolApproval::Policy,
            ToolApproval::Always,
        ]
        .into_iter()
        .map(ToolApproval::as_str)
        .collect::<Vec<_>>(),
        vec!["never", "policy", "always"]
    );
    assert_eq!(
        [
            ToolIdempotency::NotApplicable,
            ToolIdempotency::Optional,
            ToolIdempotency::Required,
        ]
        .into_iter()
        .map(ToolIdempotency::as_str)
        .collect::<Vec<_>>(),
        vec!["not_applicable", "optional", "required"]
    );
    assert_eq!(
        [
            ToolCancellation::Unsupported,
            ToolCancellation::Cooperative,
            ToolCancellation::ForceTerminable,
        ]
        .into_iter()
        .map(ToolCancellation::as_str)
        .collect::<Vec<_>>(),
        vec!["unsupported", "cooperative", "force_terminable"]
    );
    assert_eq!(
        [
            ToolResultMode::Value,
            ToolResultMode::Incremental,
            ToolResultMode::BoundedSequence,
            ToolResultMode::ArtifactReference,
        ]
        .into_iter()
        .map(ToolResultMode::as_str)
        .collect::<Vec<_>>(),
        vec![
            "value",
            "incremental",
            "bounded_sequence",
            "artifact_reference",
        ]
    );
    assert_eq!(
        [
            ToolEffect::None,
            ToolEffect::ExternalRead,
            ToolEffect::ExternalWrite,
            ToolEffect::FilesystemRead,
            ToolEffect::FilesystemWrite,
            ToolEffect::Process,
            ToolEffect::Network,
            ToolEffect::Destructive,
        ]
        .into_iter()
        .map(ToolEffect::as_str)
        .collect::<Vec<_>>(),
        vec![
            "none",
            "external_read",
            "external_write",
            "filesystem_read",
            "filesystem_write",
            "process",
            "network",
            "destructive",
        ]
    );

    assert_eq!(
        [
            ToolCallDraftStatus::Proposed,
            ToolCallDraftStatus::ArgumentsStreaming,
            ToolCallDraftStatus::ArgumentsComplete,
        ]
        .into_iter()
        .map(ToolCallDraftStatus::as_str)
        .collect::<Vec<_>>(),
        vec!["proposed", "arguments_streaming", "arguments_complete"]
    );
    assert_eq!(
        [
            ToolCallStatus::Validated,
            ToolCallStatus::PolicyPending,
            ToolCallStatus::ApprovalPending,
            ToolCallStatus::Admitted,
            ToolCallStatus::Running,
            ToolCallStatus::Completed,
            ToolCallStatus::Failed,
            ToolCallStatus::Denied,
            ToolCallStatus::Cancelled,
            ToolCallStatus::PolicyStopped,
            ToolCallStatus::Expired,
        ]
        .into_iter()
        .map(ToolCallStatus::as_str)
        .collect::<Vec<_>>(),
        vec![
            "validated",
            "policy_pending",
            "approval_pending",
            "admitted",
            "running",
            "completed",
            "failed",
            "denied",
            "cancelled",
            "policy_stopped",
            "expired",
        ]
    );
    assert_eq!(
        [
            ToolResultStatus::Completed,
            ToolResultStatus::Failed,
            ToolResultStatus::Denied,
            ToolResultStatus::Cancelled,
            ToolResultStatus::PolicyStopped,
            ToolResultStatus::Incomplete,
        ]
        .into_iter()
        .map(ToolResultStatus::as_str)
        .collect::<Vec<_>>(),
        vec![
            "completed",
            "failed",
            "denied",
            "cancelled",
            "policy_stopped",
            "incomplete",
        ]
    );
    assert_eq!(
        [
            ToolEffectOutcome::NoExternalEffect,
            ToolEffectOutcome::Committed,
            ToolEffectOutcome::NotCommitted,
            ToolEffectOutcome::Unknown,
        ]
        .into_iter()
        .map(ToolEffectOutcome::as_str)
        .collect::<Vec<_>>(),
        vec![
            "no_external_effect",
            "committed",
            "not_committed",
            "unknown",
        ]
    );
}
