#!/usr/bin/env python3
"""Verify or regenerate the platform-independent Python development lock."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
import difflib
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
import subprocess
import sys
from tempfile import TemporaryDirectory
import tomllib

from packaging.requirements import InvalidRequirement, Requirement
from packaging.utils import canonicalize_name


ROOT = Path(__file__).resolve().parents[1]
SOURCE_PATH = ROOT / "pyproject.toml"
LOCK_PATH = ROOT / "requirements" / "dev.lock"
PIP_TOOLS_VERSION = "7.6.0"
LOCK_HEADER = (
    f"# Generated by pip-tools {PIP_TOOLS_VERSION} from pyproject.toml's test extra.\n"
    "# Regenerate with: python tools/check_dev_lock.py --write\n\n"
)
FORBIDDEN_MARKER_NAMES = frozenset(
    {
        "os_name",
        "platform_machine",
        "platform_release",
        "platform_system",
        "platform_version",
        "sys_platform",
    }
)


class DevLockError(ValueError):
    """Raised when the development lock is missing, stale, or non-portable."""


def compile_command(output_path: Path, *, constrain_existing: bool) -> tuple[str, ...]:
    command = [
        sys.executable,
        "-m",
        "piptools",
        "compile",
        "--extra",
        "test",
        "--resolver",
        "backtracking",
        "--strip-extras",
        "--no-header",
        "--no-emit-index-url",
        "--quiet",
    ]
    if constrain_existing:
        command.extend(("--constraint", str(LOCK_PATH.relative_to(ROOT))))
    command.extend(
        (
            "--output-file",
            str(output_path),
            SOURCE_PATH.name,
        )
    )
    return tuple(command)


def _installed_pip_tools_version() -> str:
    try:
        return version("pip-tools")
    except PackageNotFoundError as error:
        raise DevLockError(
            f"pip-tools {PIP_TOOLS_VERSION} is required to verify the development lock"
        ) from error


def _compile_lock_body(*, constrain_existing: bool) -> str:
    installed = _installed_pip_tools_version()
    if installed != PIP_TOOLS_VERSION:
        raise DevLockError(
            f"pip-tools {PIP_TOOLS_VERSION} is required; found {installed}"
        )
    with TemporaryDirectory(prefix="graphblocks-dev-lock-") as directory:
        output_path = Path(directory) / "dev.lock"
        completed = subprocess.run(
            compile_command(
                output_path,
                constrain_existing=constrain_existing,
            ),
            cwd=ROOT,
            check=False,
            capture_output=True,
            text=True,
        )
        if completed.returncode != 0:
            diagnostic = completed.stderr.strip() or completed.stdout.strip()
            raise DevLockError(
                "pip-tools could not regenerate the development lock"
                + (f": {diagnostic}" if diagnostic else "")
            )
        try:
            return output_path.read_text(encoding="utf-8")
        except OSError as error:
            raise DevLockError(
                "pip-tools did not produce a development lock"
            ) from error


def _required_project_dependencies() -> frozenset[str]:
    try:
        project = tomllib.loads(SOURCE_PATH.read_text(encoding="utf-8"))["project"]
        dependencies = [
            *project["dependencies"],
            *project["optional-dependencies"]["test"],
        ]
    except (KeyError, OSError, TypeError, tomllib.TOMLDecodeError) as error:
        raise DevLockError("pyproject test dependencies cannot be loaded") from error
    try:
        return frozenset(
            canonicalize_name(Requirement(item).name) for item in dependencies
        )
    except InvalidRequirement as error:
        raise DevLockError(
            "pyproject contains an invalid dependency requirement"
        ) from error


def validate_lock(lock_text: str) -> frozenset[str]:
    if not lock_text.startswith(LOCK_HEADER):
        raise DevLockError("development lock header or generator version is invalid")
    locked_names: set[str] = set()
    for line_number, raw_line in enumerate(lock_text.splitlines(), start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if raw_line != line:
            raise DevLockError(
                f"development lock line {line_number} must be a pin or comment"
            )
        try:
            requirement = Requirement(line)
        except InvalidRequirement as error:
            raise DevLockError(
                f"development lock line {line_number} is not a valid requirement"
            ) from error
        if requirement.url is not None or requirement.extras:
            raise DevLockError(
                f"development lock line {line_number} must not use URLs or extras"
            )
        specifiers = tuple(requirement.specifier)
        if (
            len(specifiers) != 1
            or specifiers[0].operator != "=="
            or specifiers[0].version.endswith(".*")
        ):
            raise DevLockError(
                f"development lock line {line_number} must use one exact version pin"
            )
        marker = str(requirement.marker) if requirement.marker is not None else ""
        if any(name in marker for name in FORBIDDEN_MARKER_NAMES):
            raise DevLockError(
                f"development lock line {line_number} contains a platform marker"
            )
        name = canonicalize_name(requirement.name)
        if name in locked_names:
            raise DevLockError(f"development lock contains duplicate package {name!r}")
        locked_names.add(name)
    missing = _required_project_dependencies() - locked_names
    if missing:
        raise DevLockError(
            "development lock is missing direct dependencies: "
            + ", ".join(sorted(missing))
        )
    return frozenset(locked_names)


def rendered_lock(*, constrain_existing: bool) -> str:
    body = _compile_lock_body(constrain_existing=constrain_existing).lstrip()
    rendered = LOCK_HEADER + body
    validate_lock(rendered)
    return rendered


def check_dev_lock(*, write: bool = False) -> int:
    if write:
        generated = rendered_lock(constrain_existing=False)
        LOCK_PATH.write_text(generated, encoding="utf-8", newline="\n")
        print(f"updated {LOCK_PATH.relative_to(ROOT)}")
        return 0
    try:
        committed = LOCK_PATH.read_text(encoding="utf-8")
    except OSError as error:
        raise DevLockError("development lock cannot be read") from error
    validate_lock(committed)
    generated = rendered_lock(constrain_existing=True)
    committed_pins = tuple(
        line.strip()
        for line in committed.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )
    generated_pins = tuple(
        line.strip()
        for line in generated.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )
    if committed_pins != generated_pins:
        difference = "".join(
            difflib.unified_diff(
                [f"{line}\n" for line in committed_pins],
                [f"{line}\n" for line in generated_pins],
                fromfile="requirements/dev.lock pins",
                tofile="regenerated development lock pins",
            )
        )
        raise DevLockError(
            "development lock drifted; run python tools/check_dev_lock.py --write"
            + (f"\n{difference}" if difference else "")
        )
    print(
        "development lock passed: "
        f"{len(validate_lock(committed))} exact platform-independent pins"
    )
    return 0


def _parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        action="store_true",
        help="regenerate the committed lock with the pinned pip-tools version",
    )
    return parser.parse_args(argv)


def main(argv: Sequence[str] | None = None) -> int:
    args = _parse_args(sys.argv[1:] if argv is None else argv)
    try:
        return check_dev_lock(write=args.write)
    except DevLockError as error:
        print(f"development lock check failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
