#!/usr/bin/env python3
"""Validate CommonMark links, GitHub anchors, and generated documentation."""

from __future__ import annotations

import argparse
from bisect import bisect_right
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
import hashlib
import html
from html.parser import HTMLParser
import json
import os
from pathlib import Path, PurePosixPath
import re
import stat
import subprocess
import sys
from urllib.parse import quote, unquote, urlsplit

from github_slugger import GithubSlugger
from markdown_it import MarkdownIt
from markdown_it.rules_inline.image import image as _parse_image
from markdown_it.rules_inline.link import link as _parse_link
from markdown_it.rules_inline.state_inline import StateInline
from markdown_it.token import Token
import yaml


CHECKER_PATH = Path(__file__).resolve()
ROOT = CHECKER_PATH.parents[1]
GENERATED_REGISTRY_PATH = PurePosixPath("docs/project/generated-documentation.yaml")
MAX_DOCUMENTS = 2_048
MAX_DOCUMENT_BYTES = 4 * 1024 * 1024
MAX_TOTAL_DOCUMENT_BYTES = 64 * 1024 * 1024
MAX_REGISTRY_BYTES = 256 * 1024
MAX_EVIDENCE_FILE_BYTES = 32 * 1024 * 1024
IGNORED_DIRECTORIES = frozenset(
    {
        ".git",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".tox",
        ".venv",
        "__pycache__",
        "build",
        "dist",
        "node_modules",
        "target",
    }
)
EXTERNAL_SCHEMES = frozenset({"data", "ftp", "http", "https", "mailto", "tel"})
PROJECTION_ID = re.compile(r"[a-z][a-z0-9-]*")
LINE_FRAGMENT = re.compile(r"L(?P<start>[1-9][0-9]*)(?:-L(?P<end>[1-9][0-9]*))?")
GENERATED_MARKER = re.compile(
    r"\A\s*Generated by\s+`?"
    r"(?P<generator>tools/[A-Za-z0-9_./-]+\.py)`?[^<>]*\Z"
)
UNRESOLVED_REFERENCE_PREFIX = "graphblocks-unresolved-reference:"
ISSUE_ID_SHORTCUT_LABEL = re.compile(r"[A-Z][A-Z0-9_-]*-[0-9]+")
GFM_ALERT_LINE = re.compile(
    r"\s*(?:>\s*)+\[!(?:NOTE|TIP|IMPORTANT|WARNING|CAUTION)\]\s*"
)
# GFM alert directives and the risk register's heading IDs are literal bracketed
# text. Explicit/collapsed references and images with the same labels still fail.
REFERENCE_PROBE_RECORDS = "graphblocks_reference_probe_records"
REFERENCE_PROBE_ROOT = "graphblocks_reference_probe_root"


class DocsCheckError(RuntimeError):
    """The documentation tree or checker contract is unsafe or malformed."""


class _UniqueKeyLoader(yaml.SafeLoader):
    pass


class _ReferenceProbe(dict[str, object]):
    def get(self, key: object, default: object = None) -> object:
        if type(key) is not str:
            return default
        if key in self:
            return super().get(key, default)
        return {
            "href": UNRESOLVED_REFERENCE_PREFIX + quote(key, safe=""),
            "title": "",
        }


class _HtmlScanner(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.attributes: list[tuple[int, str, str, str]] = []
        self.comments: list[tuple[int, str]] = []

    def _record_attributes(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        line = self.getpos()[0]
        self.attributes.extend(
            (line, tag.casefold(), name.casefold(), value)
            for name, value in attrs
            if value is not None
        )

    def handle_starttag(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        self._record_attributes(tag, attrs)

    def handle_startendtag(
        self,
        tag: str,
        attrs: list[tuple[str, str | None]],
    ) -> None:
        self._record_attributes(tag, attrs)

    def handle_comment(self, data: str) -> None:
        self.comments.append((self.getpos()[0], data))


def _record_reference_rule(
    state: StateInline,
    silent: bool,
    *,
    image: bool,
) -> bool:
    start = state.pos
    label_start = start + (2 if image else 1)
    label_end = state.md.helpers.parseLinkLabel(
        state,
        start + (1 if image else 0),
        not image,
    )
    explicit = label_end >= 0 and (
        label_end + 1 < state.posMax and state.src[label_end + 1] == "["
    )
    previous_token_count = len(state.tokens)
    matched = _parse_image(state, silent) if image else _parse_link(state, silent)
    if (
        not matched
        or silent
        or state.src != state.env.get(REFERENCE_PROBE_ROOT)
        or label_end < label_start
    ):
        return matched
    token_type = "image" if image else "link_open"
    attribute = "src" if image else "href"
    for token in state.tokens[previous_token_count:]:
        if token.type != token_type:
            continue
        target = token.attrGet(attribute)
        if target and target.startswith(UNRESOLVED_REFERENCE_PREFIX):
            records = state.env.get(REFERENCE_PROBE_RECORDS)
            if isinstance(records, list):
                records.append(
                    (
                        start,
                        unquote(target.removeprefix(UNRESOLVED_REFERENCE_PREFIX)),
                        state.src[label_start:label_end],
                        not explicit,
                        image,
                    )
                )
            break
    return matched


def _record_link_reference(state: StateInline, silent: bool) -> bool:
    return _record_reference_rule(state, silent, image=False)


def _record_image_reference(state: StateInline, silent: bool) -> bool:
    return _record_reference_rule(state, silent, image=True)


def _construct_unique_mapping(
    loader: _UniqueKeyLoader,
    node: yaml.nodes.MappingNode,
    deep: bool = False,
) -> dict[object, object]:
    mapping: dict[object, object] = {}
    for key_node, value_node in node.value:
        key = loader.construct_object(key_node, deep=deep)
        try:
            duplicate = key in mapping
        except TypeError as error:
            raise DocsCheckError(
                "generated-documentation registry keys must be scalar"
            ) from error
        if duplicate:
            raise DocsCheckError(
                f"generated-documentation registry repeats YAML key {key!r}"
            )
        mapping[key] = loader.construct_object(value_node, deep=deep)
    return mapping


_UniqueKeyLoader.add_constructor(
    yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG,
    _construct_unique_mapping,
)


@dataclass(frozen=True)
class _Blob:
    data: bytes
    sha256: str


@dataclass(frozen=True)
class _Link:
    line: int
    target: str


@dataclass(frozen=True)
class _Document:
    path: Path
    relative_path: str
    text: str
    sha256: str
    tokens: tuple[Token, ...]
    references: Mapping[str, object]


@dataclass(frozen=True)
class _Projection:
    projection_id: str
    generator: str
    arguments: tuple[str, ...]
    sources: tuple[str, ...]
    outputs: tuple[str, ...]


@dataclass(frozen=True)
class _GeneratedRegistry:
    projections: tuple[_Projection, ...]
    commands: tuple[str, ...]
    digest: str


@dataclass(frozen=True)
class _CheckResult:
    failures: tuple[str, ...]
    local_links_checked: int
    external_links_skipped: int
    document_set_digest: str


def _canonical_json_bytes(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")


def _sha256(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def _read_regular_file(path: Path, *, owner: str, max_bytes: int) -> _Blob:
    try:
        metadata = path.lstat()
    except OSError as error:
        raise DocsCheckError(f"{owner} is missing or unreadable: {path}") from error
    if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
        raise DocsCheckError(f"{owner} must be a regular non-symlink file: {path}")
    if metadata.st_size > max_bytes:
        raise DocsCheckError(f"{owner} exceeds {max_bytes} bytes: {path}")
    try:
        with path.open("rb") as stream:
            data = stream.read(max_bytes + 1)
            opened_metadata = os.fstat(stream.fileno())
    except OSError as error:
        raise DocsCheckError(f"{owner} is unreadable: {path}") from error
    if len(data) > max_bytes:
        raise DocsCheckError(f"{owner} exceeds {max_bytes} bytes: {path}")
    if not os.path.samestat(metadata, opened_metadata) or (
        metadata.st_size,
        metadata.st_mtime_ns,
        metadata.st_ctime_ns,
    ) != (
        opened_metadata.st_size,
        opened_metadata.st_mtime_ns,
        opened_metadata.st_ctime_ns,
    ):
        raise DocsCheckError(f"{owner} changed while it was read: {path}")
    return _Blob(data=data, sha256=_sha256(data))


def discover_markdown_documents(root: Path) -> tuple[Path, ...]:
    """Return living Markdown files while pruning dependency and build trees."""

    resolved_root = root.resolve()
    if not resolved_root.is_dir():
        raise DocsCheckError(f"repository root is not a directory: {resolved_root}")
    documents: list[Path] = []
    for current_root, directory_names, file_names in os.walk(
        resolved_root,
        topdown=True,
        followlinks=False,
    ):
        current = Path(current_root)
        directory_names[:] = sorted(
            name
            for name in directory_names
            if name not in IGNORED_DIRECTORIES and not (current / name).is_symlink()
        )
        for name in sorted(file_names):
            path = current / name
            if path.suffix.lower() != ".md":
                continue
            if path.is_symlink():
                raise DocsCheckError(
                    "Markdown documents must not be symlinks: "
                    f"{path.relative_to(resolved_root).as_posix()}"
                )
            documents.append(path)
            if len(documents) > MAX_DOCUMENTS:
                raise DocsCheckError(
                    f"documentation tree exceeds {MAX_DOCUMENTS} Markdown files"
                )
    return tuple(documents)


def _load_documents(root: Path, paths: tuple[Path, ...]) -> tuple[_Document, ...]:
    resolved_root = root.resolve()
    if len(paths) > MAX_DOCUMENTS:
        raise DocsCheckError(
            f"documentation tree exceeds {MAX_DOCUMENTS} Markdown files"
        )
    parser = MarkdownIt("commonmark", {"html": True})
    documents: list[_Document] = []
    seen_paths: set[Path] = set()
    total_bytes = 0
    for supplied_path in sorted(paths, key=lambda value: str(value)):
        unresolved_path = (
            supplied_path
            if supplied_path.is_absolute()
            else resolved_root / supplied_path
        )
        blob = _read_regular_file(
            unresolved_path,
            owner="Markdown document",
            max_bytes=MAX_DOCUMENT_BYTES,
        )
        path = unresolved_path.resolve()
        try:
            relative = path.relative_to(resolved_root).as_posix()
        except ValueError as error:
            raise DocsCheckError(
                f"Markdown document escapes repository: {path}"
            ) from error
        if path in seen_paths:
            raise DocsCheckError(f"Markdown document is selected twice: {relative}")
        seen_paths.add(path)
        total_bytes += len(blob.data)
        if total_bytes > MAX_TOTAL_DOCUMENT_BYTES:
            raise DocsCheckError(
                f"Markdown document set exceeds {MAX_TOTAL_DOCUMENT_BYTES} total bytes"
            )
        try:
            text = blob.data.decode("utf-8")
        except UnicodeError as error:
            raise DocsCheckError(
                f"Markdown document is not valid UTF-8: {relative}"
            ) from error
        environment: dict[str, object] = {}
        try:
            tokens = tuple(parser.parse(text, environment))
        except (RuntimeError, RecursionError, ValueError) as error:
            raise DocsCheckError(
                f"CommonMark parse failed for {relative}: {error}"
            ) from error
        references = environment.get("references", {})
        if not isinstance(references, Mapping):
            raise DocsCheckError(
                f"CommonMark reference environment is malformed for {relative}"
            )
        documents.append(
            _Document(
                path=path,
                relative_path=relative,
                text=text,
                sha256=blob.sha256,
                tokens=tokens,
                references=references,
            )
        )
    return tuple(documents)


def _token_line(token: Token) -> int:
    return token.map[0] + 1 if token.map else 1


def _heading_text(inline: Token) -> str:
    parts: list[str] = []
    for child in inline.children or ():
        if child.type in {"text", "code_inline"}:
            parts.append(child.content)
        elif child.type == "image":
            parts.append(child.content)
        elif child.type in {"softbreak", "hardbreak"}:
            parts.append(" ")
    return "".join(parts)


def _parse_inline_children(
    content: str,
    references: Mapping[str, object],
    *,
    owner: str,
) -> tuple[Token, ...]:
    parser = MarkdownIt("commonmark", {"html": True})
    environment = {"references": references}
    try:
        inline_tokens = parser.parseInline(content, environment)
    except (RuntimeError, RecursionError, ValueError) as error:
        raise DocsCheckError(
            f"CommonMark inline parse failed for {owner}: {error}"
        ) from error
    return tuple(
        child for inline_token in inline_tokens for child in inline_token.children or ()
    )


def _inline_children_by_line(
    document: _Document,
    token: Token,
) -> tuple[tuple[int, tuple[Token, ...]], ...]:
    if token.map is None:
        return ()
    source_lines = document.text.splitlines()
    children_by_line: list[tuple[int, tuple[Token, ...]]] = []
    for line_index in range(token.map[0], min(token.map[1], len(source_lines))):
        children = _parse_inline_children(
            source_lines[line_index],
            document.references,
            owner=f"{document.relative_path}:{line_index + 1}",
        )
        children_by_line.append((line_index + 1, children))
    return tuple(children_by_line)


def _inline_html_fragments(
    document: _Document,
    token: Token,
) -> tuple[tuple[int, str], ...]:
    semantic_fragments = [
        child.content for child in token.children or () if child.type == "html_inline"
    ]
    candidates = [
        (line, child.content)
        for line, children in _inline_children_by_line(document, token)
        for child in children
        if child.type == "html_inline"
    ]
    fragments: list[tuple[int, str]] = []
    candidate_index = 0
    for fragment in semantic_fragments:
        while (
            candidate_index < len(candidates)
            and candidates[candidate_index][1] != fragment
        ):
            candidate_index += 1
        if candidate_index < len(candidates):
            fragments.append(candidates[candidate_index])
            candidate_index += 1
        else:
            fragments.append((_token_line(token), fragment))
    return tuple(fragments)


def _html_fragments(document: _Document) -> tuple[tuple[int, str], ...]:
    fragments: list[tuple[int, str]] = []
    for token in document.tokens:
        if token.type == "html_block":
            fragments.append((_token_line(token), token.content))
        if token.type == "inline":
            fragments.extend(_inline_html_fragments(document, token))
    return tuple(fragments)


def _scan_html(raw_html: str, *, owner: str) -> _HtmlScanner:
    scanner = _HtmlScanner()
    try:
        scanner.feed(raw_html)
        scanner.close()
    except (AssertionError, RuntimeError, ValueError) as error:
        raise DocsCheckError(f"HTML parse failed for {owner}: {error}") from error
    return scanner


def _document_generated_markers(document: _Document) -> tuple[str, ...]:
    markers: list[str] = []
    for line, raw_html in _html_fragments(document):
        scanner = _scan_html(raw_html, owner=f"{document.relative_path}:{line}")
        for _, comment in scanner.comments:
            match = GENERATED_MARKER.fullmatch(comment)
            if match is not None:
                markers.append(match.group("generator"))
    return tuple(markers)


def _document_anchors(document: _Document) -> tuple[dict[str, int], list[str]]:
    anchors: dict[str, int] = {}
    failures: list[str] = []
    slugger = GithubSlugger()
    declarations: list[tuple[int, int, str]] = []
    declaration_order = 0
    for index, token in enumerate(document.tokens):
        if token.type == "heading_open" and index + 1 < len(document.tokens):
            inline = document.tokens[index + 1]
            if inline.type != "inline":
                raise DocsCheckError(
                    f"CommonMark heading lacks inline content in {document.relative_path}"
                )
            anchor = slugger.slug(_heading_text(inline))
            if anchor:
                line = _token_line(token)
                declarations.append((line, declaration_order, anchor))
                declaration_order += 1
    for line, raw_html in _html_fragments(document):
        scanner = _scan_html(raw_html, owner=f"{document.relative_path}:{line}")
        for line_offset, tag, name, value in scanner.attributes:
            if name != "id" and not (tag == "a" and name == "name"):
                continue
            anchor = value
            declarations.append((line + line_offset - 1, declaration_order, anchor))
            declaration_order += 1
    for line, _, anchor in sorted(declarations):
        if anchor in anchors:
            failures.append(
                f"{document.relative_path}:{line}: duplicate Markdown anchor "
                f"#{anchor} (first declared on line {anchors[anchor]})"
            )
        else:
            anchors[anchor] = line
    return anchors, failures


def _unresolved_references(
    document: _Document,
    token: Token,
) -> tuple[tuple[int, str], ...]:
    records: list[tuple[int, str, str, bool, bool]] = []
    probe = _ReferenceProbe(document.references)
    parser = MarkdownIt("commonmark", {"html": True})
    parser.inline.ruler.at("link", _record_link_reference)
    parser.inline.ruler.at("image", _record_image_reference)
    environment = {
        "references": probe,
        REFERENCE_PROBE_RECORDS: records,
        REFERENCE_PROBE_ROOT: token.content,
    }
    try:
        parser.parseInline(token.content, environment)
    except (RuntimeError, RecursionError, ValueError) as error:
        raise DocsCheckError(
            f"CommonMark reference probe failed for "
            f"{document.relative_path}:{_token_line(token)}: {error}"
        ) from error
    line_starts = [0]
    line_starts.extend(
        index + 1 for index, character in enumerate(token.content) if character == "\n"
    )
    source_lines = document.text.splitlines()
    unresolved: list[tuple[int, str]] = []
    for position, label, raw_label, shortcut, image in sorted(set(records)):
        line = _token_line(token) + bisect_right(line_starts, position) - 1
        if shortcut and not image:
            if ISSUE_ID_SHORTCUT_LABEL.fullmatch(raw_label):
                continue
            if raw_label.startswith("!") and GFM_ALERT_LINE.fullmatch(
                source_lines[line - 1]
            ):
                continue
        unresolved.append((line, label.casefold()))
    return tuple(dict.fromkeys(unresolved))


def _link_targets(children: Sequence[Token], *, owner: str) -> tuple[str, ...]:
    targets: list[str] = []
    for child in children:
        if child.type == "link_open":
            target = child.attrGet("href")
            if target:
                targets.append(target)
        elif child.type == "image":
            target = child.attrGet("src")
            if target:
                targets.append(target)
        elif child.type == "html_inline":
            scanner = _scan_html(child.content, owner=owner)
            targets.extend(
                value
                for _, _, name, value in scanner.attributes
                if name in {"href", "src"}
            )
    return tuple(targets)


def _document_links(document: _Document) -> tuple[tuple[_Link, ...], list[str]]:
    links: list[_Link] = []
    failures: list[str] = []
    seen: set[tuple[int, str]] = set()

    def add(line: int, target: object) -> None:
        if type(target) is not str or not target:
            return
        identity = (line, target)
        if identity not in seen:
            seen.add(identity)
            links.append(_Link(line=line, target=target))

    for reference in document.references.values():
        if not isinstance(reference, Mapping):
            raise DocsCheckError(
                f"CommonMark reference is malformed in {document.relative_path}"
            )
        line_map = reference.get("map")
        line = (
            line_map[0] + 1
            if isinstance(line_map, Sequence)
            and len(line_map) == 2
            and type(line_map[0]) is int
            else 1
        )
        add(line, reference.get("href"))

    for token in document.tokens:
        line = _token_line(token)
        if token.type == "html_block":
            scanner = _scan_html(
                token.content,
                owner=f"{document.relative_path}:{line}",
            )
            for line_offset, _, name, value in scanner.attributes:
                if name in {"href", "src"}:
                    add(line + line_offset - 1, value)
        if token.type != "inline":
            continue
        for reference_line, reference in _unresolved_references(document, token):
            failures.append(
                f"{document.relative_path}:{reference_line}: "
                f"unresolved Markdown reference "
                f"[{reference}]"
            )
        semantic_targets = _link_targets(
            token.children or (),
            owner=f"{document.relative_path}:{line}",
        )
        candidates = [
            (candidate_line, target)
            for candidate_line, children in _inline_children_by_line(document, token)
            for target in _link_targets(
                children,
                owner=f"{document.relative_path}:{candidate_line}",
            )
        ]
        candidate_index = 0
        for target in semantic_targets:
            while (
                candidate_index < len(candidates)
                and candidates[candidate_index][1] != target
            ):
                candidate_index += 1
            if candidate_index < len(candidates):
                add(*candidates[candidate_index])
                candidate_index += 1
            else:
                add(line, target)
    return tuple(links), failures


def _path_has_exact_case(root: Path, path: Path) -> bool:
    try:
        relative_parts = path.relative_to(root).parts
    except ValueError:
        return False
    current = root
    for part in relative_parts:
        try:
            names = {entry.name for entry in current.iterdir()}
        except OSError:
            return False
        if part not in names:
            return False
        current /= part
    return True


def _read_repository_file(
    root: Path,
    relative_path: str,
    *,
    owner: str,
    max_bytes: int,
) -> _Blob:
    lexical_path = root / relative_path
    if not _path_has_exact_case(root, lexical_path):
        raise DocsCheckError(f"{owner} is missing or case-mismatched: {relative_path}")
    try:
        resolved_path = lexical_path.resolve(strict=True)
        resolved_path.relative_to(root)
    except (OSError, ValueError) as error:
        raise DocsCheckError(
            f"{owner} escapes the repository: {relative_path}"
        ) from error
    if resolved_path != lexical_path:
        raise DocsCheckError(f"{owner} must not traverse symlinks: {relative_path}")
    return _read_regular_file(lexical_path, owner=owner, max_bytes=max_bytes)


def _line_fragment_exists(path: Path, fragment: str) -> bool:
    match = LINE_FRAGMENT.fullmatch(fragment)
    if match is None:
        return False
    blob = _read_regular_file(
        path,
        owner="line-fragment target",
        max_bytes=MAX_EVIDENCE_FILE_BYTES,
    )
    try:
        line_count = len(blob.data.decode("utf-8").splitlines())
    except UnicodeError:
        return False
    start = int(match.group("start"))
    end = int(match.group("end") or start)
    return start <= end <= line_count


def _check_loaded_documents(
    root: Path,
    documents: tuple[_Document, ...],
) -> _CheckResult:
    resolved_root = root.resolve()
    failures: list[str] = []
    anchors_by_path: dict[Path, dict[str, int]] = {}
    for document in documents:
        anchors, anchor_failures = _document_anchors(document)
        anchors_by_path[document.path] = anchors
        failures.extend(anchor_failures)

    local_links_checked = 0
    external_links_skipped = 0
    for document in documents:
        links, reference_failures = _document_links(document)
        failures.extend(reference_failures)
        for link in links:
            raw_target = html.unescape(link.target.strip())
            try:
                parsed = urlsplit(raw_target)
            except ValueError:
                failures.append(
                    f"{document.relative_path}:{link.line}: malformed Markdown link: "
                    f"{raw_target}"
                )
                continue
            if parsed.scheme.lower() in EXTERNAL_SCHEMES or raw_target.startswith("//"):
                external_links_skipped += 1
                continue
            local_links_checked += 1
            decoded_path = unquote(parsed.path)
            if (
                parsed.scheme
                or parsed.netloc
                or decoded_path.startswith("/")
                or "\\" in decoded_path
                or "\x00" in decoded_path
            ):
                failures.append(
                    f"{document.relative_path}:{link.line}: unsupported local link: "
                    f"{raw_target}"
                )
                continue
            lexical_path = Path(
                os.path.abspath(
                    document.path
                    if not decoded_path
                    else document.path.parent / decoded_path
                )
            )
            try:
                lexical_relative = lexical_path.relative_to(resolved_root).as_posix()
            except ValueError:
                failures.append(
                    f"{document.relative_path}:{link.line}: local link escapes the "
                    f"repository: {raw_target}"
                )
                continue
            if not lexical_path.exists() or not _path_has_exact_case(
                resolved_root, lexical_path
            ):
                failures.append(
                    f"{document.relative_path}:{link.line}: local link target does not "
                    f"exist: {raw_target}"
                )
                continue
            target_path = lexical_path.resolve()
            try:
                target_relative = target_path.relative_to(resolved_root).as_posix()
            except ValueError:
                failures.append(
                    f"{document.relative_path}:{link.line}: local link escapes the "
                    f"repository through a symlink: {raw_target}"
                )
                continue
            fragment = unquote(parsed.fragment)
            if not fragment:
                continue
            if target_path.suffix.lower() == ".md" and target_path.is_file():
                anchors = anchors_by_path.get(target_path)
                if anchors is None:
                    target_document = _load_documents(resolved_root, (target_path,))[0]
                    anchors, anchor_failures = _document_anchors(target_document)
                    anchors_by_path[target_path] = anchors
                    failures.extend(anchor_failures)
                if fragment not in anchors:
                    failures.append(
                        f"{document.relative_path}:{link.line}: Markdown fragment does "
                        f"not exist in {target_relative}: #{fragment}"
                    )
                continue
            if not target_path.is_file() or not _line_fragment_exists(
                target_path, fragment
            ):
                failures.append(
                    f"{document.relative_path}:{link.line}: source line fragment does "
                    f"not exist in {lexical_relative}: #{fragment}"
                )

    document_records = [
        {"path": document.relative_path, "sha256": document.sha256}
        for document in documents
    ]
    return _CheckResult(
        failures=tuple(sorted(set(failures))),
        local_links_checked=local_links_checked,
        external_links_skipped=external_links_skipped,
        document_set_digest=_sha256(_canonical_json_bytes(document_records)),
    )


def check_markdown_documents(root: Path, paths: tuple[Path, ...]) -> list[str]:
    """Return deterministic diagnostics for CommonMark links and GitHub anchors."""

    documents = _load_documents(root, paths)
    return list(_check_loaded_documents(root, documents).failures)


def _require_exact_mapping(
    value: object,
    keys: set[str],
    *,
    owner: str,
) -> dict[str, object]:
    if not isinstance(value, Mapping) or set(value) != keys:
        raise DocsCheckError(f"{owner} must have the exact closed shape")
    if any(type(key) is not str for key in value):
        raise DocsCheckError(f"{owner} keys must be strings")
    return dict(value)


def _safe_repository_path(value: object, *, owner: str) -> str:
    if type(value) is not str or not value or value != value.strip():
        raise DocsCheckError(f"{owner} must be a non-empty trimmed path")
    path = PurePosixPath(value)
    if (
        path.is_absolute()
        or path.as_posix() != value
        or "\\" in value
        or any(part in {"", ".", ".."} for part in path.parts)
    ):
        raise DocsCheckError(f"{owner} must be a normalized repository path")
    return value


def _path_array(value: object, *, owner: str) -> tuple[str, ...]:
    if not isinstance(value, list) or not value:
        raise DocsCheckError(f"{owner} must be a non-empty path array")
    paths = tuple(
        _safe_repository_path(item, owner=f"{owner}[{index}]")
        for index, item in enumerate(value)
    )
    if len(paths) != len(set(paths)):
        raise DocsCheckError(f"{owner} must not contain duplicate paths")
    return paths


def _load_generated_registry(
    root: Path, documents: tuple[_Document, ...]
) -> _GeneratedRegistry:
    registry_relative_path = GENERATED_REGISTRY_PATH.as_posix()
    blob = _read_repository_file(
        root,
        registry_relative_path,
        owner="generated-documentation registry",
        max_bytes=MAX_REGISTRY_BYTES,
    )
    try:
        raw_registry = yaml.load(blob.data.decode("utf-8"), Loader=_UniqueKeyLoader)
    except (UnicodeError, yaml.YAMLError) as error:
        raise DocsCheckError(
            "generated-documentation registry is not valid UTF-8 YAML"
        ) from error
    registry = _require_exact_mapping(
        raw_registry,
        {"formatVersion", "projections"},
        owner="generated-documentation registry",
    )
    if type(registry.get("formatVersion")) is not int or registry["formatVersion"] != 1:
        raise DocsCheckError("generated-documentation formatVersion must equal 1")
    raw_projections = registry.get("projections")
    if not isinstance(raw_projections, list) or not raw_projections:
        raise DocsCheckError(
            "generated-documentation projections must be a non-empty array"
        )

    projections: list[_Projection] = []
    ids: set[str] = set()
    generators: set[str] = set()
    outputs_seen: set[str] = set()
    digest_records: list[dict[str, object]] = []
    for index, raw_projection in enumerate(raw_projections):
        projection = _require_exact_mapping(
            raw_projection,
            {"id", "generator", "arguments", "sources", "outputs"},
            owner=f"generated-documentation projection {index}",
        )
        projection_id = projection.get("id")
        if (
            type(projection_id) is not str
            or PROJECTION_ID.fullmatch(projection_id) is None
            or projection_id in ids
        ):
            raise DocsCheckError(
                "generated-documentation projection ids must be unique kebab-case"
            )
        generator = _safe_repository_path(
            projection.get("generator"),
            owner=f"generated-documentation projection {projection_id} generator",
        )
        if (
            not generator.startswith("tools/")
            or not generator.endswith(".py")
            or generator in generators
        ):
            raise DocsCheckError(
                "generated-documentation generators must be unique tools/*.py paths"
            )
        arguments = projection.get("arguments")
        if arguments != ["--check"]:
            raise DocsCheckError(
                f"generated-documentation projection {projection_id} must use --check"
            )
        sources = _path_array(
            projection.get("sources"),
            owner=f"generated-documentation projection {projection_id} sources",
        )
        outputs = _path_array(
            projection.get("outputs"),
            owner=f"generated-documentation projection {projection_id} outputs",
        )
        if not any(output.endswith(".md") for output in outputs):
            raise DocsCheckError(
                f"generated-documentation projection {projection_id} has no Markdown output"
            )
        if outputs_seen.intersection(outputs):
            raise DocsCheckError(
                "generated-documentation output paths must have one owner"
            )
        ids.add(projection_id)
        generators.add(generator)
        outputs_seen.update(outputs)
        normalized = _Projection(
            projection_id=projection_id,
            generator=generator,
            arguments=("--check",),
            sources=sources,
            outputs=outputs,
        )
        projections.append(normalized)

        files: list[dict[str, str]] = []
        for path in (generator, *sources, *outputs):
            file_blob = _read_repository_file(
                root,
                path,
                owner=f"generated-documentation projection {projection_id} evidence",
                max_bytes=MAX_EVIDENCE_FILE_BYTES,
            )
            files.append({"path": path, "sha256": file_blob.sha256})
        digest_records.append(
            {
                "id": projection_id,
                "generator": generator,
                "arguments": ["--check"],
                "files": files,
            }
        )

    marker_outputs: dict[str, list[str]] = {}
    for document in documents:
        for generator in _document_generated_markers(document):
            marker_outputs.setdefault(generator, []).append(document.relative_path)
    if set(marker_outputs) != generators:
        raise DocsCheckError(
            "generated-documentation markers and registry generators differ "
            f"(markers={sorted(marker_outputs)}, registry={sorted(generators)})"
        )
    documents_by_path = {document.relative_path: document for document in documents}
    for projection in projections:
        markdown_outputs = {
            output for output in projection.outputs if output.endswith(".md")
        }
        missing_outputs = sorted(markdown_outputs - documents_by_path.keys())
        if missing_outputs:
            raise DocsCheckError(
                f"generated-documentation Markdown outputs are not living documents: "
                f"{missing_outputs}"
            )
        marked_outputs = marker_outputs[projection.generator]
        if len(marked_outputs) != len(set(marked_outputs)):
            raise DocsCheckError(
                f"generated-documentation output repeats the marker for "
                f"{projection.projection_id}"
            )
        if set(marked_outputs) != markdown_outputs:
            raise DocsCheckError(
                f"generated-documentation output ownership differs for "
                f"{projection.projection_id} "
                f"(markers={sorted(marked_outputs)}, "
                f"registry={sorted(markdown_outputs)})"
            )

    digest_payload = {
        "manifest": {
            "path": GENERATED_REGISTRY_PATH.as_posix(),
            "sha256": blob.sha256,
        },
        "projections": digest_records,
    }
    return _GeneratedRegistry(
        projections=tuple(projections),
        commands=tuple(
            " ".join((projection.generator, *projection.arguments))
            for projection in projections
        ),
        digest=_sha256(_canonical_json_bytes(digest_payload)),
    )


def _run_generated_checks(root: Path, registry: _GeneratedRegistry) -> list[str]:
    failures: list[str] = []
    for projection in registry.projections:
        command = (projection.generator, *projection.arguments)
        try:
            completed = subprocess.run(
                [sys.executable, *command],
                cwd=root,
                check=False,
                capture_output=True,
                text=True,
                timeout=60,
            )
        except (OSError, subprocess.TimeoutExpired) as error:
            failures.append(
                f"generated documentation check failed to run: {' '.join(command)}: "
                f"{error}"
            )
            continue
        if completed.returncode != 0:
            output = (completed.stderr or completed.stdout).strip()
            failures.append(
                f"generated documentation is stale: {' '.join(command)}"
                + (f": {output}" if output else "")
            )
    return failures


def _write_report(path: Path, payload: dict[str, object]) -> None:
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(_canonical_json_bytes(payload) + b"\n")
    except OSError as error:
        raise DocsCheckError(
            f"documentation report could not be written: {path}"
        ) from error


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args(argv)

    root = args.root.resolve()
    try:
        document_paths = discover_markdown_documents(root)
        documents = _load_documents(root, document_paths)
        result = _check_loaded_documents(root, documents)
        registry = _load_generated_registry(root, documents)
        generated_failures = _run_generated_checks(root, registry)
        checker_digest = _read_regular_file(
            CHECKER_PATH,
            owner="documentation checker",
            max_bytes=MAX_EVIDENCE_FILE_BYTES,
        ).sha256
    except DocsCheckError as error:
        parser.exit(2, f"documentation check failed: {error}\n")
    failures = [*result.failures, *generated_failures]
    report: dict[str, object] = {
        "formatVersion": 1,
        "status": "failed" if failures else "passed",
        "checkerDigest": checker_digest,
        "documentsChecked": len(documents),
        "localLinksChecked": result.local_links_checked,
        "externalLinksSkipped": result.external_links_skipped,
        "documentSetDigest": result.document_set_digest,
        "generatedProjectionDigest": registry.digest,
        "generatedChecks": list(registry.commands),
    }
    if failures:
        report["failures"] = failures
    report["resultDigest"] = _sha256(_canonical_json_bytes(report))
    if args.report is not None:
        try:
            _write_report(args.report.resolve(), report)
        except DocsCheckError as error:
            parser.exit(2, f"documentation check failed: {error}\n")
    if failures:
        for failure in failures:
            print(failure, file=sys.stderr)
        return 1
    print(
        f"documentation checks passed: {len(documents)} documents, "
        f"{result.local_links_checked} local links, {report['resultDigest']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
